<!DOCTYPE tvSchedule [
    <!ELEMENT tvSchedule (channel+)>
    <!ELEMENT channel (banner,day+)>
    <!ELEMENT banner (#PCDATA)>
    <!ELEMENT day (date,(holiday|programSlot+)+)>
    <!ELEMENT holiday (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT programSlot (time,title,description?)>
    <!ELEMENT time (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ATTLIST tvSchedule name CDATA #REQUIRED>
    <!ATTLIST channel chan CDATA #REQUIRED>
    <!ATTLIST programSlot vtr CDATA #IMPLIED>
    <!ATTLIST title rating CDATA #IMPLIED>
    <!ATTLIST title language CDATA #IMPLIED>
]>
<!--<?xml version="1.0" encoding="UTF-8"?>-->

<tvSchedule name="Text">
    <channel chan="Text">
        <banner>Text</banner>
        <day>
            <date>Text</date>
            <holiday>Text</holiday>
            <programSlot vtr="Text">
                <time>Text</time>
                <title rating="Text" language="Text">Text</title>
                <description>Text</description>
            </programSlot>
        </day>
    </channel>
</tvSchedule>