
<!DOCTYPE newspaper [
<!ELEMENT newspaper (article+)>
<!ELEMENT article (headline,byline,lead,body,notes)>
<!ELEMENT headline (#PCDATA)>
<!ELEMENT byline (#PCDATA)>
<!ELEMENT lead (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

<!ATTLIST article author CDATA #REQUIRED>
<!ATTLIST article editor CDATA #IMPLIED>
<!ATTLIST article date CDATA #IMPLIED>
<!ATTLIST article edition CDATA #IMPLIED>

<!ENTITY newspaper "Vervet Logic Times">
<!ENTITY publisher "Vervet Logic Press">
<!ENTITY copyright "Copyright 1998 Vervet Logic Press">
]>

<!--<?xml version="1.0" encoding="UTF-8"?>-->

<newspaper>
    <article author="A" editor="B" data="C" edition="D">
        <headline>Text</headline>
        <byline>Text</byline>
        <lead>&newspaper;</lead>
        <body>&copyright;</body>
        <notes>&publisher;</notes>
    </article>
</newspaper>
