<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE artists [
    <!ELEMENT artists (performer*)>
    <!ELEMENT performer ((name | nick*)*, born)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT nick (#PCDATA)>
    <!ELEMENT born (#PCDATA)>
]>
<artists>
    <performer>
        <name>Antonio Vivaldi</name>
        <nick>The redheaded priest</nick>
        <born>4-03-1678</born>
    </performer>
    <performer>
        <name>Johann Sebastian Bach</name>
        <nick>The old wig</nick>
        <born>21-03-1685</born>
    </performer>
</artists>