=== ariadna-aldeguer/DAM/Schema/Repaso/Ex1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="laboratori">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="grups">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="grup" maxOccurs="4">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nom" type="xs:string"/>
                                    <xs:element name="informe" minOccurs="0">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="nom" type="xs:string"/>
                                                <xs:element name="any" type="xs:integer"/>
                                                <xs:element name="descripcio" type="xs:string"/>
                                                <xs:element name="responsable" minOccurs="0">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="nom" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="autors"> 
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="nom" type="xs:string" maxOccurs="unbounded"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>    
                    </xs:sequence>
                </xs:complexType>
            </xs:element>                
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== ariadna-aldeguer/DAM/Schema/Repaso/Ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<laboratori xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ex1.xsd">
    <nom>CERN</nom>
    <grups>
        <grup>
            <nom>Noves Tecnologies</nom>
            <informe>
                <nom> Information Management: a proposal</nom>
                <any>1989</any>
                <descripcio>Definició de les bases de l&apos;actual World Wide Web. </descripcio>
                <responsable>
                    <nom>Mike Sendall</nom>
                </responsable>
                <autors>
                    <nom>Tim Berners-Lee</nom>
                    <nom>Robert Cailliau</nom>
                </autors>
            </informe>
        </grup>
        <grup>
            <nom>Física de partícules</nom>
            <informe>
                <nom>The Higgs Boson explained</nom>
                <any>2012</any>
                <descripcio>Formulació de la teoria sobre un nou bosó</descripcio>
                <autors>
                    <nom>Peter Higgs</nom>
                    <nom>François Englert</nom>
                </autors>
            </informe>
        </grup>
        <grup>
            <nom>telecomunicacions</nom>
        </grup>
        <grup>
            <nom>Cosmologia</nom>
            <informe>
                <nom>Violation CP</nom>
                <any>1979</any>
                <descripcio>Detall de com les relacions subatòmiques no acompleixen els principise simetria</descripcio>
                <autors>
                    <nom>James Cronin</nom>
                    <nom>Val Fitch</nom>
                </autors>
            </informe>
        </grup>
    </grups>
</laboratori>
