=== ariadna-aldeguer/DAM/Schema/Repaso/Ex2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="desenvolupadors">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="treballador" maxOccurs="2">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"/>
                        <xs:element name="email" type="tcorreu"/>
                        <xs:element name="codi" type="xs:integer"/>
                        <xs:element name="adressa" type="tadressa"/>      
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>   
</xs:element>
 <xs:complexType name="tcorreu">
        <xs:sequence>   
            <xs:element name="mailp" type="xs:string"/>
            <xs:element name="mailc" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tadressa">
        <xs:sequence>
            <xs:element name="ciutat" type="xs:string"/>
            <xs:element name="provincia" type="xs:string"/>
            <xs:element name="codpos" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ariadna-aldeguer/DAM/Schema/Repaso/Ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<desenvolupadors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ex2.xsd">
    <nom>Desenvolupadors Back-End</nom>
    <treballador>
        <nom>Perico Palotes</nom>
        <email>
            <mailp>perico@gmail.com</mailp>
            <mailc>perpal@empresa.com</mailc>
        </email>
        <codi>78956</codi>
        <adressa>
            <ciutat>Barcelona</ciutat>
            <provincia>Barcelona</provincia>
            <codpos>08080</codpos>
        </adressa>
    </treballador>
    <treballador>
        <nom>Maria Antonieta</nom>
        <email>
            <mailp>maria@gmail.com</mailp>
            <mailc>maran@empresa.com</mailc>
        </email>
        <codi>54682</codi>
        <adressa>
            <ciutat>Barcelona</ciutat>
            <provincia>Barcelona</provincia>
            <codpos>08080</codpos>
        </adressa>
    </treballador>
</desenvolupadors>
