=== ariadna-aldeguer/DAM/Schema/Repaso/Ex3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="nom" type="xs:string"/>
    <xs:element name="qualificacio" type="xs:string"/>
    <xs:element name="naixement" type="xs:date"/>
    <xs:element name="defuncio" type="xs:date"/>
    <xs:element name="isbn" type="xs:integer"/>
    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="available" type="xs:boolean"/>
    <xs:attribute name="lang" type="xs:language"/>
    <xs:element name="titol">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="lang"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="llibreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="llibre" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="autor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="naixement"/>
                <xs:element ref="defuncio" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="llibre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="isbn"/>
                <xs:element ref="titol"/>
                <xs:element ref="autor" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="personatge" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
            <xs:attribute ref="available"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="personatge">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom"/>
                <xs:element ref="naixement"/>
                <xs:element ref="qualificacio"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ariadna-aldeguer/DAM/Schema/Repaso/Ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<llibreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ex3.xsd">
    <llibre id="AER" available="true">
        <isbn>1254</isbn>
        <titol lang="ES">PCDATA</titol>
        <autor id="ERO">
            <nom>PCDATA</nom>
            <naixement>1995-05-05</naixement>
            <defuncio>2010-08-12</defuncio>
        </autor>
        <personatge id="QWE">
            <nom>PCDATA</nom>
            <naixement>1995-05-05</naixement>
            <qualificacio>Nota: 9</qualificacio>
        </personatge>
    </llibre>
    <llibre id="AER" available="true">
        <isbn>1254</isbn>
        <titol lang="ES">PCDATA</titol>
        <autor id="ERO">
            <nom>PCDATA</nom>
            <naixement>1995-05-05</naixement>
            <defuncio>2010-08-12</defuncio>
        </autor>
        <personatge id="QWE">
            <nom>PCDATA</nom>
            <naixement>1995-05-05</naixement>
            <qualificacio>Nota: 9</qualificacio>
        </personatge>
    </llibre>
</llibreria>
