=== ariadna-aldeguer/DAM/Schema/Repaso/Ex4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="agenda">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="company">
                    <xs:complexType>
                        <xs:all minOccurs="0">
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="edat">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="adult" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="correu" type="xs:string"/>
                            <xs:element name="ubicacio">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="aula" type="xs:integer"/>
                                            <xs:attribute name="planta" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="residencia" type="xs:string"/>
                        </xs:all>
                        <xs:attribute name="id" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ariadna-aldeguer/DAM/Schema/Repaso/Ex4.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ex4.xsd">
    <company id="01">
        <nom>Jordi Sanz</nom>
        <edat adult="Sí">33</edat>
        <correu>j.sanchez@gmail.com</correu>
        <residencia>Barcelona</residencia>
        <ubicacio aula="23" planta="2">davant</ubicacio>
    </company>
    <company id="02">
        <nom>Pep Sanchez</nom>
        <correu>p.sanchez@gmail.com</correu>
        <residencia>Badalona</residencia>
        <ubicacio aula="23" planta="segona">dreta</ubicacio>
        <edat adult="Sí">23</edat>
    </company>
    <company id="03">
        <nom>Miquel Mateu</nom>
        <edat>37</edat>
        <ubicacio aula="23" planta="2">darrera</ubicacio>
        <correu>m.mateu@hotmail.com</correu>
        <residencia>Cerdanyola</residencia>
    </company>
    <company id="04">
        <nom>Mireia Sanchis</nom>
        <edat adult="Sí">33</edat>
        <correu>j.sanchez@gmail.com</correu>
        <residencia>Sabadell</residencia>
        <ubicacio aula="23" planta="2">esquerra</ubicacio>
    </company>
</agenda>
